version: '3.9'

services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql$08
      MYSQL_DATABASE: proref-db
    volumes:
      - db:/home/hydra/Documents/docker-db/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_net
    restart: always

  phpmyadmin:
    container_name: phpmyadmin5.2.1_container
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mysql$08
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_net
    restart: always

volumes:
  db:
    driver: local

networks:
  app_net:
    driver: bridge
